require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OptionValuesController do

  # This should return the minimal set of attributes required to create a valid
  # OptionValue. As you add validations to OptionValue, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OptionValuesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all option_values as @option_values" do
      option_value = OptionValue.create! valid_attributes
      get :index, {}, valid_session
      assigns(:option_values).should eq([option_value])
    end
  end

  describe "GET show" do
    it "assigns the requested option_value as @option_value" do
      option_value = OptionValue.create! valid_attributes
      get :show, {:id => option_value.to_param}, valid_session
      assigns(:option_value).should eq(option_value)
    end
  end

  describe "GET new" do
    it "assigns a new option_value as @option_value" do
      get :new, {}, valid_session
      assigns(:option_value).should be_a_new(OptionValue)
    end
  end

  describe "GET edit" do
    it "assigns the requested option_value as @option_value" do
      option_value = OptionValue.create! valid_attributes
      get :edit, {:id => option_value.to_param}, valid_session
      assigns(:option_value).should eq(option_value)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new OptionValue" do
        expect {
          post :create, {:option_value => valid_attributes}, valid_session
        }.to change(OptionValue, :count).by(1)
      end

      it "assigns a newly created option_value as @option_value" do
        post :create, {:option_value => valid_attributes}, valid_session
        assigns(:option_value).should be_a(OptionValue)
        assigns(:option_value).should be_persisted
      end

      it "redirects to the created option_value" do
        post :create, {:option_value => valid_attributes}, valid_session
        response.should redirect_to(OptionValue.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved option_value as @option_value" do
        # Trigger the behavior that occurs when invalid params are submitted
        OptionValue.any_instance.stub(:save).and_return(false)
        post :create, {:option_value => { "name" => "invalid value" }}, valid_session
        assigns(:option_value).should be_a_new(OptionValue)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        OptionValue.any_instance.stub(:save).and_return(false)
        post :create, {:option_value => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested option_value" do
        option_value = OptionValue.create! valid_attributes
        # Assuming there are no other option_values in the database, this
        # specifies that the OptionValue created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        OptionValue.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => option_value.to_param, :option_value => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested option_value as @option_value" do
        option_value = OptionValue.create! valid_attributes
        put :update, {:id => option_value.to_param, :option_value => valid_attributes}, valid_session
        assigns(:option_value).should eq(option_value)
      end

      it "redirects to the option_value" do
        option_value = OptionValue.create! valid_attributes
        put :update, {:id => option_value.to_param, :option_value => valid_attributes}, valid_session
        response.should redirect_to(option_value)
      end
    end

    describe "with invalid params" do
      it "assigns the option_value as @option_value" do
        option_value = OptionValue.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OptionValue.any_instance.stub(:save).and_return(false)
        put :update, {:id => option_value.to_param, :option_value => { "name" => "invalid value" }}, valid_session
        assigns(:option_value).should eq(option_value)
      end

      it "re-renders the 'edit' template" do
        option_value = OptionValue.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OptionValue.any_instance.stub(:save).and_return(false)
        put :update, {:id => option_value.to_param, :option_value => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested option_value" do
      option_value = OptionValue.create! valid_attributes
      expect {
        delete :destroy, {:id => option_value.to_param}, valid_session
      }.to change(OptionValue, :count).by(-1)
    end

    it "redirects to the option_values list" do
      option_value = OptionValue.create! valid_attributes
      delete :destroy, {:id => option_value.to_param}, valid_session
      response.should redirect_to(option_values_url)
    end
  end

end
