require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VariantProductsController do

  # This should return the minimal set of attributes required to create a valid
  # VariantProduct. As you add validations to VariantProduct, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VariantProductsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all variant_products as @variant_products" do
      variant_product = VariantProduct.create! valid_attributes
      get :index, {}, valid_session
      assigns(:variant_products).should eq([variant_product])
    end
  end

  describe "GET show" do
    it "assigns the requested variant_product as @variant_product" do
      variant_product = VariantProduct.create! valid_attributes
      get :show, {:id => variant_product.to_param}, valid_session
      assigns(:variant_product).should eq(variant_product)
    end
  end

  describe "GET new" do
    it "assigns a new variant_product as @variant_product" do
      get :new, {}, valid_session
      assigns(:variant_product).should be_a_new(VariantProduct)
    end
  end

  describe "GET edit" do
    it "assigns the requested variant_product as @variant_product" do
      variant_product = VariantProduct.create! valid_attributes
      get :edit, {:id => variant_product.to_param}, valid_session
      assigns(:variant_product).should eq(variant_product)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new VariantProduct" do
        expect {
          post :create, {:variant_product => valid_attributes}, valid_session
        }.to change(VariantProduct, :count).by(1)
      end

      it "assigns a newly created variant_product as @variant_product" do
        post :create, {:variant_product => valid_attributes}, valid_session
        assigns(:variant_product).should be_a(VariantProduct)
        assigns(:variant_product).should be_persisted
      end

      it "redirects to the created variant_product" do
        post :create, {:variant_product => valid_attributes}, valid_session
        response.should redirect_to(VariantProduct.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved variant_product as @variant_product" do
        # Trigger the behavior that occurs when invalid params are submitted
        VariantProduct.any_instance.stub(:save).and_return(false)
        post :create, {:variant_product => {  }}, valid_session
        assigns(:variant_product).should be_a_new(VariantProduct)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        VariantProduct.any_instance.stub(:save).and_return(false)
        post :create, {:variant_product => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested variant_product" do
        variant_product = VariantProduct.create! valid_attributes
        # Assuming there are no other variant_products in the database, this
        # specifies that the VariantProduct created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        VariantProduct.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => variant_product.to_param, :variant_product => { "these" => "params" }}, valid_session
      end

      it "assigns the requested variant_product as @variant_product" do
        variant_product = VariantProduct.create! valid_attributes
        put :update, {:id => variant_product.to_param, :variant_product => valid_attributes}, valid_session
        assigns(:variant_product).should eq(variant_product)
      end

      it "redirects to the variant_product" do
        variant_product = VariantProduct.create! valid_attributes
        put :update, {:id => variant_product.to_param, :variant_product => valid_attributes}, valid_session
        response.should redirect_to(variant_product)
      end
    end

    describe "with invalid params" do
      it "assigns the variant_product as @variant_product" do
        variant_product = VariantProduct.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VariantProduct.any_instance.stub(:save).and_return(false)
        put :update, {:id => variant_product.to_param, :variant_product => {  }}, valid_session
        assigns(:variant_product).should eq(variant_product)
      end

      it "re-renders the 'edit' template" do
        variant_product = VariantProduct.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VariantProduct.any_instance.stub(:save).and_return(false)
        put :update, {:id => variant_product.to_param, :variant_product => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested variant_product" do
      variant_product = VariantProduct.create! valid_attributes
      expect {
        delete :destroy, {:id => variant_product.to_param}, valid_session
      }.to change(VariantProduct, :count).by(-1)
    end

    it "redirects to the variant_products list" do
      variant_product = VariantProduct.create! valid_attributes
      delete :destroy, {:id => variant_product.to_param}, valid_session
      response.should redirect_to(variant_products_url)
    end
  end

end
