require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VariantPropertiesController do

  # This should return the minimal set of attributes required to create a valid
  # VariantProperty. As you add validations to VariantProperty, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "primary" => "false" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VariantPropertiesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all variant_properties as @variant_properties" do
      variant_property = VariantProperty.create! valid_attributes
      get :index, {}, valid_session
      assigns(:variant_properties).should eq([variant_property])
    end
  end

  describe "GET show" do
    it "assigns the requested variant_property as @variant_property" do
      variant_property = VariantProperty.create! valid_attributes
      get :show, {:id => variant_property.to_param}, valid_session
      assigns(:variant_property).should eq(variant_property)
    end
  end

  describe "GET new" do
    it "assigns a new variant_property as @variant_property" do
      get :new, {}, valid_session
      assigns(:variant_property).should be_a_new(VariantProperty)
    end
  end

  describe "GET edit" do
    it "assigns the requested variant_property as @variant_property" do
      variant_property = VariantProperty.create! valid_attributes
      get :edit, {:id => variant_property.to_param}, valid_session
      assigns(:variant_property).should eq(variant_property)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new VariantProperty" do
        expect {
          post :create, {:variant_property => valid_attributes}, valid_session
        }.to change(VariantProperty, :count).by(1)
      end

      it "assigns a newly created variant_property as @variant_property" do
        post :create, {:variant_property => valid_attributes}, valid_session
        assigns(:variant_property).should be_a(VariantProperty)
        assigns(:variant_property).should be_persisted
      end

      it "redirects to the created variant_property" do
        post :create, {:variant_property => valid_attributes}, valid_session
        response.should redirect_to(VariantProperty.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved variant_property as @variant_property" do
        # Trigger the behavior that occurs when invalid params are submitted
        VariantProperty.any_instance.stub(:save).and_return(false)
        post :create, {:variant_property => { "primary" => "invalid value" }}, valid_session
        assigns(:variant_property).should be_a_new(VariantProperty)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        VariantProperty.any_instance.stub(:save).and_return(false)
        post :create, {:variant_property => { "primary" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested variant_property" do
        variant_property = VariantProperty.create! valid_attributes
        # Assuming there are no other variant_properties in the database, this
        # specifies that the VariantProperty created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        VariantProperty.any_instance.should_receive(:update).with({ "primary" => "false" })
        put :update, {:id => variant_property.to_param, :variant_property => { "primary" => "false" }}, valid_session
      end

      it "assigns the requested variant_property as @variant_property" do
        variant_property = VariantProperty.create! valid_attributes
        put :update, {:id => variant_property.to_param, :variant_property => valid_attributes}, valid_session
        assigns(:variant_property).should eq(variant_property)
      end

      it "redirects to the variant_property" do
        variant_property = VariantProperty.create! valid_attributes
        put :update, {:id => variant_property.to_param, :variant_property => valid_attributes}, valid_session
        response.should redirect_to(variant_property)
      end
    end

    describe "with invalid params" do
      it "assigns the variant_property as @variant_property" do
        variant_property = VariantProperty.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VariantProperty.any_instance.stub(:save).and_return(false)
        put :update, {:id => variant_property.to_param, :variant_property => { "primary" => "invalid value" }}, valid_session
        assigns(:variant_property).should eq(variant_property)
      end

      it "re-renders the 'edit' template" do
        variant_property = VariantProperty.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VariantProperty.any_instance.stub(:save).and_return(false)
        put :update, {:id => variant_property.to_param, :variant_property => { "primary" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested variant_property" do
      variant_property = VariantProperty.create! valid_attributes
      expect {
        delete :destroy, {:id => variant_property.to_param}, valid_session
      }.to change(VariantProperty, :count).by(-1)
    end

    it "redirects to the variant_properties list" do
      variant_property = VariantProperty.create! valid_attributes
      delete :destroy, {:id => variant_property.to_param}, valid_session
      response.should redirect_to(variant_properties_url)
    end
  end

end
