require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VariantProductOptionTypesController do

  # This should return the minimal set of attributes required to create a valid
  # VariantProductOptionType. As you add validations to VariantProductOptionType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VariantProductOptionTypesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all variant_product_option_types as @variant_product_option_types" do
      variant_product_option_type = VariantProductOptionType.create! valid_attributes
      get :index, {}, valid_session
      assigns(:variant_product_option_types).should eq([variant_product_option_type])
    end
  end

  describe "GET show" do
    it "assigns the requested variant_product_option_type as @variant_product_option_type" do
      variant_product_option_type = VariantProductOptionType.create! valid_attributes
      get :show, {:id => variant_product_option_type.to_param}, valid_session
      assigns(:variant_product_option_type).should eq(variant_product_option_type)
    end
  end

  describe "GET new" do
    it "assigns a new variant_product_option_type as @variant_product_option_type" do
      get :new, {}, valid_session
      assigns(:variant_product_option_type).should be_a_new(VariantProductOptionType)
    end
  end

  describe "GET edit" do
    it "assigns the requested variant_product_option_type as @variant_product_option_type" do
      variant_product_option_type = VariantProductOptionType.create! valid_attributes
      get :edit, {:id => variant_product_option_type.to_param}, valid_session
      assigns(:variant_product_option_type).should eq(variant_product_option_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new VariantProductOptionType" do
        expect {
          post :create, {:variant_product_option_type => valid_attributes}, valid_session
        }.to change(VariantProductOptionType, :count).by(1)
      end

      it "assigns a newly created variant_product_option_type as @variant_product_option_type" do
        post :create, {:variant_product_option_type => valid_attributes}, valid_session
        assigns(:variant_product_option_type).should be_a(VariantProductOptionType)
        assigns(:variant_product_option_type).should be_persisted
      end

      it "redirects to the created variant_product_option_type" do
        post :create, {:variant_product_option_type => valid_attributes}, valid_session
        response.should redirect_to(VariantProductOptionType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved variant_product_option_type as @variant_product_option_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        VariantProductOptionType.any_instance.stub(:save).and_return(false)
        post :create, {:variant_product_option_type => { "name" => "invalid value" }}, valid_session
        assigns(:variant_product_option_type).should be_a_new(VariantProductOptionType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        VariantProductOptionType.any_instance.stub(:save).and_return(false)
        post :create, {:variant_product_option_type => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested variant_product_option_type" do
        variant_product_option_type = VariantProductOptionType.create! valid_attributes
        # Assuming there are no other variant_product_option_types in the database, this
        # specifies that the VariantProductOptionType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        VariantProductOptionType.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => variant_product_option_type.to_param, :variant_product_option_type => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested variant_product_option_type as @variant_product_option_type" do
        variant_product_option_type = VariantProductOptionType.create! valid_attributes
        put :update, {:id => variant_product_option_type.to_param, :variant_product_option_type => valid_attributes}, valid_session
        assigns(:variant_product_option_type).should eq(variant_product_option_type)
      end

      it "redirects to the variant_product_option_type" do
        variant_product_option_type = VariantProductOptionType.create! valid_attributes
        put :update, {:id => variant_product_option_type.to_param, :variant_product_option_type => valid_attributes}, valid_session
        response.should redirect_to(variant_product_option_type)
      end
    end

    describe "with invalid params" do
      it "assigns the variant_product_option_type as @variant_product_option_type" do
        variant_product_option_type = VariantProductOptionType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VariantProductOptionType.any_instance.stub(:save).and_return(false)
        put :update, {:id => variant_product_option_type.to_param, :variant_product_option_type => { "name" => "invalid value" }}, valid_session
        assigns(:variant_product_option_type).should eq(variant_product_option_type)
      end

      it "re-renders the 'edit' template" do
        variant_product_option_type = VariantProductOptionType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VariantProductOptionType.any_instance.stub(:save).and_return(false)
        put :update, {:id => variant_product_option_type.to_param, :variant_product_option_type => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested variant_product_option_type" do
      variant_product_option_type = VariantProductOptionType.create! valid_attributes
      expect {
        delete :destroy, {:id => variant_product_option_type.to_param}, valid_session
      }.to change(VariantProductOptionType, :count).by(-1)
    end

    it "redirects to the variant_product_option_types list" do
      variant_product_option_type = VariantProductOptionType.create! valid_attributes
      delete :destroy, {:id => variant_product_option_type.to_param}, valid_session
      response.should redirect_to(variant_product_option_types_url)
    end
  end

end
